### PR TITLE
Changed clowder_enabled into class method

### PR DESCRIPTION
**Pull request by hsong-rh**
Need to know if clowder is enabled before initializing the config instance

### CODE REVIEW

**Comment by hsong-rh** [comment]
@slemrmartin Please review

**Comment by mkanoor** [comment]
@hsong-rh Can you move all the class methods together so they stand out

**Review by slemrmartin — APPROVED** [review]
:+1:

**Comment by slemrmartin** [comment]
@hsong-rh also change the example in Readme

**Comment by slemrmartin** [comment]
@hsong-rh also change the example in Readme

**Comment by hsong-rh** [comment]
@slemrmartin README was changed accordingly.

**Review by mkanoor — APPROVED** [review]

**Pull request merged**
